### ISSUE TITLE
Crashes after connect

### ISSUE THREAD

**Issue by tony-sol** [containers/podman-tui#551]
**Describe the bug**
podman-tui crashes right after connection

**To Reproduce**
- start podman machine
- run podman-tui

**Expected behavior**
app do not crash

**Screenshots**

https://github.com/user-attachments/assets/5172c49e-2bea-495c-b8e2-f044814f0809

**Desktop (please complete the following information):**
 - OS macos 15.2 (24C101)
 - Podman Version 5.3.2
 - Podman TUI version  v1.3.0

**Additional context**

`podman-tui --debug --log-file ~/podman-tui.log':
```log
2025-01-25T01:43:51+03:00 INF starting podman-tui version 1.3.0 in debug mode
2025-01-25T01:43:51+03:00 DBG env set CONTAINER_PASSPHRASE="__empty__"
2025-01-25T01:43:51+03:00 DBG app: new application
2025-01-25T01:43:51+03:00 DBG config: new
2025-01-25T01:43:51+03:00 DBG config: reading configuration file "/Users/anton.solovev/.config/podman-tui/podman-tui.conf"
2025-01-25T01:43:51+03:00 DBG pdcs: registry set connection {default false disconnected unix:///Users/anton.solovev/.local/share/containers/podman/machine/podman.sock }
2025-01-25T01:43:51+03:00 INF app: run
2025-01-25T01:43:51+03:00 DBG app: starting refresh loop (interval=1s)
2025-01-25T01:43:51+03:00 DBG app: starting fast refresh loop
2025-01-25T01:43:52+03:00 DBG app: switching to system screen
2025-01-25T01:43:53+03:00 DBG pdcs: podman pod ls
2025-01-25T01:43:53+03:00 DBG pdcs: []
2025-01-25T01:43:53+03:00 DBG pdcs: podman container ls
2025-01-25T01:43:53+03:00 DBG pdcs: []
2025-01-25T01:43:53+03:00 DBG pdcs: podman network ls
2025-01-25T01:43:53+03:00 DBG pdcs: [[2f259bab93aaaaa2542ba43ef33eb990d0999ee1b9924b557b7be53c0b7a1bb9 podman bridge]]
2025-01-25T01:43:53+03:00 DBG pdcs: podman image ls
2025-01-25T01:43:53+03:00 DBG pdcs: []
2025-01-25T01:43:53+03:00 DBG pdcs: podman volume ls
2025-01-25T01:43:53+03:00 DBG pdcs: []
2025-01-25T01:43:54+03:00 DBG health check: start event streamer
2025-01-25T01:43:54+03:00 DBG health check: pdcs event steamer started
2025-01-25T01:43:54+03:00 DBG health check: event reader started
2025-01-25T01:43:58+03:00 ERR health check: pdcs event streamer Get "http://d/v5.3.1/libpod/events?stream=true": EOF
2025-01-25T01:43:58+03:00 DBG health check: pdcs event steamer cancel sent
2025-01-25T01:43:58+03:00 DBG health check: pdcs event streamer stopped
2025-01-25T01:43:58+03:00 DBG health check: event reader stopped
2025-01-25T01:43:58+03:00 DBG pdcs: registry context cancel
```

related envs:
```
COLORTERM=truecolor
TERM=tmux-256color
TERMINFO=~/.local/share/terminfo
TERMINFO_DIRS=~/.local/share/terminfo:/usr/share/terminfo
TERM_PROGRAM=tmux
TERM_PROGRAM_VERSION=3.5a
```

podman-tui.conf:
```toml
[services]
  [services.default]
    default = true
    uri = "unix://${XDG_DATA_HOME}/containers/podman/machine/podman.sock"
```

`podman-tui --debug 2> ~/podman-tui.stderr.log`
```
panic: close of closed channel

goroutine 353 [running]:
github.com/containers/podman/v5/pkg/bindings/system.Events.func2()
	/private/tmp/podman-tui-20241201-4769-sibwjb/podman-tui-1.3.0/vendor/github.com/containers/podman/v5/pkg/bindings/system/system.go:58 +0x19c
created by github.com/containers/podman/v5/pkg/bindings/system.Events in goroutine 38
	/private/tmp/podman-tui-20241201-4769-sibwjb/podman-tui-1.3.0/vendor/github.com/containers/podman/v5/pkg/bindings/system/system.go:47 +0x208
```

**Comment by navidys** [comment]
Hi @tony-sol 
The issue is fixed in the main branch, can you try to build from main branch ?
Will releaes podman-tui 1.3.1 soon. 

Regards

**Comment by tony-sol** [comment]
Just updated to 1.3.1 - nop, still crashing
Log:

`podman-tui --debug 2> ~/podman-tui.log `
```
panic: close of closed channel

goroutine 867 [running]:
github.com/containers/podman/v5/pkg/bindings/system.Events.func2()
        /private/tmp/podman-tui-20250126-4759-nt0clj/podman-tui-1.3.1/vendor/github.com/containers/podman/v5/pkg/bindings/system/system.go:58 +0x19c
created by github.com/containers/podman/v5/pkg/bindings/system.Events in goroutine 24
        /private/tmp/podman-tui-20250126-4759-nt0clj/podman-tui-1.3.1/vendor/github.com/containers/podman/v5/pkg/bindings/system/system.go:47 +0x208
n {default false disconnected unix:///Users/anton.solovev/.local/share/containers/podman/machine/podman.sock }
2025-01-26T23:40:37+03:00 INF app: run
2025-01-26T23:40:37+03:00 DBG app: starting refresh loop (interval=1s)
2025-01-26T23:40:37+03:00 DBG app: starting fast refresh loop
2025-01-26T23:40:38+03:00 DBG app: switching to system screen
2025-01-26T23:40:39+03:00 DBG pdcs: podman pod ls
2025-01-26T23:40:39+03:00 DBG pdcs: []
2025-01-26T23:40:39+03:00 DBG pdcs: podman container ls
2025-01-26T23:40:39+03:00 DBG pdcs: []
2025-01-26T23:40:39+03:00 DBG pdcs: podman network ls
2025-01-26T23:40:39+03:00 DBG pdcs: [[2f259bab93aaaaa2542ba43ef33eb990d0999ee1b9924b557b7be53c0b7a1bb9 podman bridge]]
2025-01-26T23:40:39+03:00 DBG pdcs: podman image ls
2025-01-26T23:40:39+03:00 DBG pdcs: []
2025-01-26T23:40:39+03:00 DBG pdcs: podman volume ls
2025-01-26T23:40:39+03:00 DBG pdcs: []
2025-01-26T23:40:40+03:00 DBG health check: start event streamer
2025-01-26T23:40:40+03:00 DBG health check: pdcs event steamer started
2025-01-26T23:40:40+03:00 DBG health check: event reader started
2025-01-26T23:40:45+03:00 ERR health check: pdcs event streamer Get "http://d/v5.3.2/libpod/events?stream=true": EOF
2025-01-26T23:40:45+03:00 DBG health check: pdcs event steamer cancel sent
2025-01-26T23:40:45+03:00 DBG health check: pdcs event streamer stopped
2025-01-26T23:40:45+03:00 DBG health check: event reader stopped
2025-01-26T23:40:45+03:00 DBG pdcs: registry context cancel
```

**Comment by navidys** [comment]
Thank for testing @tony-sol , will update you soon.

**Comment by navidys** [comment]
Hi @tony-sol 
The issue is fixed and delivered to main branch.

I will release a new version that includes podman v4.5.0 as well soon.
